# Generated by Django 2.2.2 on 2020-11-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201109_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.FileField(default='head/default.png', upload_to='head/'),
        ),
    ]
