# Generated by Django 2.2.2 on 2020-11-10 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201109_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
    ]
