# Generated by Django 2.2.2 on 2020-11-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_token', models.CharField(max_length=255)),
                ('user_type', models.SmallIntegerField(choices=[(1, 'super_vip'), (2, 'vip'), (3, 'generic')])),
            ],
        ),
    ]
