# Generated by Django 2.2.2 on 2020-11-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_author_book_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
