# Generated by Django 2.2.2 on 2020-11-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20201116_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publish',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
