# Generated by Django 2.2.2 on 2020-11-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20201116_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(db_constraint=False, related_name='books', to='learn.Book'),
        ),
    ]
