# Generated by Django 2.2.2 on 2020-11-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20201116_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(db_constraint=False, related_name='authors', to='learn.Author'),
        ),
    ]
