# Generated by Django 2.2.2 on 2020-11-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20201116_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
