# Generated by Django 2.2.2 on 2020-11-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(db_constraint=False, to='learn.Author'),
        ),
    ]
