# Generated by Django 2.2.2 on 2020-11-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='id_delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='id_delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='publish',
            old_name='id_delete',
            new_name='is_delete',
        ),
    ]
